# .streamlit/secrets.toml

TURSO_DATABASE_URL = "libsql://footy-karanp02.aws-eu-west-1.turso.io"
TURSO_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NTkzMzY5MzksImlkIjoiOWE3ZjY2Y2QtNGY4Yi00NzExLWIxNTYtZGQzOTlmYmQxNjViIiwicmlkIjoiNDQ4MjhmMmMtMGJlMS00NzJlLWI5NjYtMGQ2NWZlY2IyOWRkIn0.Z0LP_ziuHVx4hJw9bJpHttnANuD21YlwcrOiyKcHsGx8IvqESXy7fTklMkDxb4xDGdMY65vPRlLkb0MkIL71Aw"
ADMIN_PASSWORD = "KP123"
